### ISSUE TITLE
[Good First Issues]: review Vanus Connect Documentation

### ISSUE THREAD

**Issue by JieDing** [linkall-labs/vanus-connect#131]
# Motivation

Vanus Connect allows you to skip the complex integration with external services by offering out-of-the-box connectors. 

Reviewing Vanus connector docs will be a good start if you decide to know more about Vanus Connect.

# Task List

- [x] #133 
- [x] #135 
- [x] #136
- [x] #137 

# Contribution points
Each issue counts specific points based on its difficulty. Contributors earn the corresponding points if they solve that issue. Contribution points are used to describe the contributions contributors have made. They can also be used to get rewards when there are community events.

# How to claim to solve the issue
If you want to solve a specific issue, please leave a comment in that issue like:

> I'd like to solve this issue, please assign it to me.

Vanus community will assign the issue to you on time.

**Comment by Himanshu-Vishwas** [comment]
I'd like to solve the issue, please assign it to me.

**Comment by Himanshu-Vishwas** [comment]
Hi! I am new to this repository and i would love to contribute. 

Can you please give me some pointers on how to solve this?

**Comment by Michaelg22** [comment]
Hi @Himanshu-Vishwas Please chose from the new issues this issue is completed

**Comment by Himanshu-Vishwas** [comment]
Ok thanks
