### ISSUE TITLE
[Good First Issues]: update connector doc "connectors/sink-feishu" - 2 points

### ISSUE THREAD

**Issue by JieDing** [linkall-labs/vanus-connect#133]
# Motivation
Vanus Connect allows you to skip the complex integration with external services by offering out-of-the-box connectors.

Reviewing Vanus connector docs will be a good start if you decide to know more about Vanus Connect.

# Details

Update the improper image sources in the [documentation of sink-feishu](https://github.com/linkall-labs/vance/blob/main/connectors/sink-feishu/README.md).

# How to change

1. Fork the vanus-connect repository.
2. Create a branch update-sink-feishu
3. Update file `connectors/sink-feishu/README.md`
4. Change image source `https://github.com/linkall-labs/vance-docs/raw/main/resources/connectors/sink-feishu-bot/add-a-bot.gif` to `https://github.com/linkall-labs/vance/blob/main/connectors/sink-feishu/add-a-bot.gif?raw=true`.
5. Change image source `https://github.com/linkall-labs/vance-docs/raw/main/resources/connectors/sink-feishu-bot/feishu-config.png` to `https://github.com/linkall-labs/vance/blob/main/connectors/sink-feishu/feishu-config.png?raw=true`.
6. Change image source `https://github.com/linkall-labs/vance/blob/main/connectors/sink-feishu/received-message.png` to `https://github.com/linkall-labs/vance/blob/main/connectors/sink-feishu/received-message.png?raw=true`.
7. Submit your PR

# Contribution points
Each issue counts specific points based on its difficulty. Contributors earn the corresponding points if they solve that issue. Contribution points are used to describe the contributions contributors have made. They can also be used to get rewards when there are community events.

This issue counts 2 points.

# How to claim to solve this issue
If you want to solve this issue, please leave a comment in this issue like:

> I'd like to solve the issue, please assign it to me.

Vanus community will assign the issue to you on time.

**Comment by nwokoloemmanuel6** [comment]
I'd like to solve the issue, please assign it to me

**Comment by JieDing** [comment]
> I'd like to solve the issue, please assign it to me

Amazing, assigned it to you

**Comment by Michaelg22** [comment]
This issue has been solved and merged.
