### ISSUE TITLE
[Good First Issues]: update connector doc "connectors/sink-tencentcloud-scf" - 1 point

### ISSUE THREAD

**Issue by JieDing** [linkall-labs/vanus-connect#136]
# Motivation
Vanus Connect allows you to skip the complex integration with external services by offering out-of-the-box connectors.

Reviewing Vanus connector docs will be a good start if you decide to know more about Vanus Connect.

# Details

Update the improper image sources in the [documentation of sink-tencentcloud-scf](https://github.com/linkall-labs/vance/blob/main/connectors/sink-tencentcloud-scf/README.md).

# How to change

1. Fork the vanus-connect repository.
2. Create a branch update-sink-slack
3. Update file `connectors/sink-tencentcloud-scf/README.md`
4. Change image source `https://github.com/linkall-labs/vance/blob/main/connectors/sink-tencentcloud-scf/scf-log.png` to `https://github.com/linkall-labs/vance/blob/main/connectors/sink-tencentcloud-scf/scf-log.png?raw=true`.
5. Submit your PR

# Contribution points
Each issue counts specific points based on its difficulty. Contributors earn the corresponding points if they solve that issue. Contribution points are used to describe the contributions contributors have made. They can also be used to get rewards when there are community events.

This issue counts 1 point.

# How to claim to solve this issue
If you want to solve this issue, please leave a comment in this issue like:

> I'd like to solve the issue, please assign it to me.

Vanus community will assign the issue to you on time.

**Comment by nikitakoselev** [comment]
I have raised a PR #149 for the issue.
Please let me know if anything has to be updated.

**Comment by Michaelg22** [comment]
Thank you for your contribution.
