### ISSUE TITLE
[Good First Issues]: update connector doc "connectors/source-mongodb" - 1 point

### ISSUE THREAD

**Issue by JieDing** [linkall-labs/vanus-connect#137]
# Motivation
Vanus Connect allows you to skip the complex integration with external services by offering out-of-the-box connectors.

Reviewing Vanus connector docs will be a good start if you decide to know more about Vanus Connect.

# Details

Update the improper image sources in the [documentation of source-mongodb](https://github.com/linkall-labs/vanus-connect/blob/main/connectors/source-mongodb/README.md).

# How to change

1. Fork the vanus-connect repository.
2. Create a branch update-source-mongodb
3. Update file `connectors/source-mongodb/README.md`
4. Remove the line `please see [Event Structure](#Event Structure) to understanding it.`
5. Submit your PR

# Contribution points
Each issue counts specific points based on its difficulty. Contributors earn the corresponding points if they solve that issue. Contribution points are used to describe the contributions contributors have made. They can also be used to get rewards when there are community events.

This issue counts 1 point.

# How to claim to solve this issue
If you want to solve this issue, please leave a comment in this issue like:

> I'd like to solve the issue, please assign it to me.

Vanus community will assign the issue to you on time.

**Comment by DevanshSahni** [comment]
I'd like to solve the issue, please assign it to me.

**Comment by DevanshSahni** [comment]
Hi! can you please tell me how to resolve DCO error.

**Comment by JieDing** [comment]
> Hi! can you please tell me how to resolve DCO error.

Please go through this one https://github.com/linkall-labs/docs/blob/main/CONTRIBUTING.md#sign-your-work

**Comment by gauravmnjwr** [comment]
Hey there, I've created a pull request please check.

**Comment by Michaelg22** [comment]
This issue was merged and fix please make sure to join the slack [community](https://join.slack.com/t/vanusworkspace/shared_invite/zt-1irlglugm-CHWGHKd2Nzs7yYhzEMnMlg)
